FROM node:22-alpine

RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.22/main" > /etc/apk/repositories && \
    echo "https://dl-cdn.alpinelinux.org/alpine/v3.22/community" >> /etc/apk/repositories && \
    apk update && apk add --no-cache \
    python3 make g++ libc-dev pkgconfig \
    pixman-dev cairo-dev pango-dev jpeg-dev \
    giflib-dev libpng-dev

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

EXPOSE 3000
ENV NODE_ENV development

CMD ["npm", "run", "dev"]