FROM node:18-alpine

ENV LOG_LEVEL=DEBUG

WORKDIR /apicode

# Copy package files and install dependencies
COPY package*.json tsconfig.json ./
RUN npm install

# Copy source code
COPY src/ ./src/

COPY uploads/ ./uploads/

# Compile TypeScript
RUN npm run build

# Expose backend port
EXPOSE 5001

# Start the application
CMD ["npm", "start"]